CREATE TABLE admin (
    food_id SERIAL PRIMARY KEY,
    food_name VARCHAR(100) NOT NULL,
    price VARCHAR(100) NOT NULL,
    offer VARCHAR(100) NOT NULL,
    description VARCHAR(100) NOT NULL,
    tags VARCHAR(100) NOT NULL,
    image VARCHAR(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
